### ISSUE TITLE
getting auth error, I have double checked username and password + env variables

### ISSUE THREAD

**Issue by kstenbaek** [SAP-samples/teched2024-XP280#40]
this is what I get when executing the plan

```
@kstenbaek ➜ /workspaces/teched2024-XP280/terraform_build (main) $ terraform plan -out=tfplan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # random_uuid.uuid will be created
  + resource "random_uuid" "uuid" {
      + id     = (known after apply)
      + result = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: unableToCreateClient
│ 
│   with provider["registry.terraform.io/sap/btp"],
│   on provider.tf line 12, in provider "btp":
│   12: provider "btp" {
│ 
│ Login failed. Check your credentials. [Status: 401; Correlation ID: 28e8daec-e445-e80c-acb6-7f34b7fe9a66]
╵
@kstenbaek ➜ /workspaces/teched2024-XP280/terraform_build (main) $ 
```

**Comment by sapienz-kb** [comment]
I have the same issue with a freshly created trial user, no MFA and using the P-number along with the password.
I went over SAP Note 3085908, but that did not fix the issue.

**Comment by sapienz-kb** [comment]
@lechnerc77 I had the same thought, but the issue occurred for me with a completely new, freshly created Universal ID, which only has a P-user assigned, and nothing else - no MFA either...

**Comment by lechnerc77** [comment]
@sapienz-kb Can you cross-check if you can access your account with this user when using the BTP CLI.
What could be a source of this error is a typo in the subdomain of the global account that you specify. 
And another question that helps to pin down the cause: the account is a regular SAP BTP account (trial or productive) not one of an SAP internal landscape, correct?

**Comment by lechnerc77** [comment]
Thinking out loud: 
- Subdomain for trial is always with the "-ga". You used that. Check
- As it is trial no additional configuration for the provider is needed except for the subdomain of the global account. Check 
- You tried the password via UI for the Cockpit and it worked. Check
- You added quotes around the password. Check

There are two more things we could try if you have the time and want to:

- Execute a login via BTP CLI (not SSO) interactive via console (we are using the same flow as the BTP CLI)
- Add the username and password as variables to the Terraform provider configuration (need to stress that this is bad practice, but for the sake of the analysis) in the `variables.tf` file 

```terraform
variable "username" {
  description = "BTP username"
  type        = string
  sensitive   = true

}

variable "password" {
  description = "BTP user password"
  type        = string
  sensitive   = true
}
```
- as well as setting them in the provider.tf file:

```terraform
provider "btp" {
  globalaccount = var.global_account
  username      = var.username
  password      = var.password
}
```

Do not add them to the `terraform.tfvars` file. Then execute a `terraform plan`. This will then interactively prompt you for the values of the username and password.

**Comment by lechnerc77** [comment]
If the CLI works, but the Terraform provider even when explicitly entering it, is weird. I am running out of ideas what could be the root cause for that. 
You can give the SSO parameter a try with the Terraform provider to enable the login

**Comment by kstenbaek** [comment]
> @sapienz-kb @kstenbaek assuming the prerequisites of the SAP note are in place and your Universal ID user as well as your P/S User have the same password set, this might be caused by having several S/P-Users users attached to the Universal ID i.e. using the same email that you use for authentication when leveraging the Terraform provider. In this case you can directly use the S-User/P-User ID as username for authentication of the Terraform provider.

@lechnerc77 FYI I succeeded logging in by following the instruction to login with s-user instead of universal id as described here: https://me.sap.com/notes/3085908
